name: Compila
on:
  - push
  - pull_request
jobs:
  compile-sketches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:mega2560
          sketch-paths: |
            - ADC/ADC.ino
