on:
  - push
  - pull_request
jobs:
  compile-sketches:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:megaavr:uno2018:mode=on
          sketch-paths: |
            - ADC
          libraries: |
            -name: HX711
